(define a (list 1 3 (list 5 7) 9))
(define b (list (list 7)))
(define c (list 1 (list 2 (list 3 (list 4 (list 5 (list 6 (list 7))))))))
(display (cadr (car (cdr (cdr a)))))
(display (car (car b)))
(display (car (cadr (cadr (cadr (cadr (cadr (cadr c))))))))
